require("prototypes.updates.updates")
require("prototypes.updates.updates-corpses_necro")
require("prototypes.updates.updates-corpses_bobs")
require("prototypes.updates.updates-corpses_5dim")
require("prototypes.updates.updates-technology")
