require("prototypes.categories")
require("prototypes.categories-ammo")
require("prototypes.enemies.corpses")
require("prototypes.item")
require("prototypes.recipe")
require("prototypes.recipe-artifacts")
require("prototypes.technology")
require("prototypes.fluids")
require("prototypes.projectiles")
require("prototypes.entities")
require("prototypes.walls")
require("prototypes.technology-damage-upgrades")
require("prototypes.fireball-turret")


